-- =====================================================================
-- Skema tabel lokal AI Agent (PostgreSQL) — JALANKAN MANUAL di pgAdmin.
--
-- Aplikasi TIDAK lagi membuat/menghapus tabel saat startup (tidak ada
-- create_all / drop_all). Semua DDL dikelola dari file ini.
--
-- Aman dijalankan berulang: semua memakai IF NOT EXISTS.
-- Database target: database_url di .env (DB lokal AI Agent, BUKAN DB ERP).
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1. draft_order — draft order menunggu finalisasi admin
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS draft_order (
    id             INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wa_number      VARCHAR(20)  NOT NULL,
    toko_id        VARCHAR(50)  NOT NULL,
    toko_name      VARCHAR(200) NOT NULL,
    toko_address   VARCHAR(500),
    items          JSON         NOT NULL,
    note           TEXT,
    status         VARCHAR(20)  NOT NULL DEFAULT 'pending',  -- pending | finalized | cancelled
    admin_wa       VARCHAR(20),
    so_number      VARCHAR(50),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_draft_order_wa_number ON draft_order (wa_number);
CREATE INDEX IF NOT EXISTS ix_draft_order_toko_id   ON draft_order (toko_id);


-- ---------------------------------------------------------------------
-- 2. conversation_log — audit trail percakapan
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conversation_log (
    id             INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wa_number      VARCHAR(20)  NOT NULL,
    toko_id        VARCHAR(50),
    role           VARCHAR(10)  NOT NULL,   -- user | assistant
    message        TEXT         NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_conversation_log_wa_number
    ON conversation_log (wa_number);


-- ---------------------------------------------------------------------
-- 3. aiso_counter — counter nomor SO per-periode (YYMM)
--    Format nomor akhir: AISO/YYMM/NNNNN (NNNNN reset tiap bulan).
--    Increment dilakukan atomik (SELECT ... FOR UPDATE) di aplikasi.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aiso_counter (
    periode    VARCHAR(4)  PRIMARY KEY,         -- 'YYMM'
    last_seq   INTEGER     NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------
-- 4. wiser_order — audit & idempotensi push final order ke Wiser.
--    Satu baris = satu upaya kirim.
--    externalid (PK) dipakai sebagai tasksalesid di payload Wiser;
--    noso sebagai tasksalesnoso.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wiser_order (
    externalid     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    noso           VARCHAR(30)  NOT NULL,
    sotype         VARCHAR(20)  NOT NULL,
    toko_id        VARCHAR(50),
    tokoidwarisan  VARCHAR(50),
    draft_order_id INTEGER,
    status         VARCHAR(20)  NOT NULL DEFAULT 'pending',  -- pending | success | failed
    wisertosopid   BIGINT,
    errormessage   TEXT,
    payload        TEXT,                                     -- JSON request
    response       TEXT,                                     -- JSON response
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_wiser_order_noso_sotype UNIQUE (noso, sotype)
);
CREATE INDEX IF NOT EXISTS ix_wiser_order_noso           ON wiser_order (noso);
CREATE INDEX IF NOT EXISTS ix_wiser_order_toko_id        ON wiser_order (toko_id);
CREATE INDEX IF NOT EXISTS ix_wiser_order_draft_order_id ON wiser_order (draft_order_id);
